Repository sliit-foss/timekeeper-web, pull requests merged in 2023-07, with the labels that each got.

#24 Fix(console): now resembles the design
  package.json
  pnpm-lock.yaml
  src/components/common/blocks/heading.jsx
  src/components/common/blocks/index.jsx
  src/components/common/blocks/insight.jsx
  src/components/common/blocks/preview.jsx
  src/components/common/index.jsx
  src/components/common/layout/footer.jsx
  src/components/common/layout/header.jsx
  src/components/common/layout/index.jsx
  src/components/landing/console.jsx
  src/components/landing/console/example.jsx
  src/components/landing/console/index.jsx
  src/components/landing/hero.jsx
  src/components/landing/vision/index.jsx
  src/components/landing/vision/timeline.jsx
  src/pages/landing.jsx
Labels: changed requested :eyes:, enhancement

#42 Feat(hero): added animation for the logo
  src/components/common/layout/footer.jsx
  src/components/landing/hero.jsx
  src/icons/index.jsx
  src/icons/timekeeper-animated.jsx
  src/icons/timekeeper.jsx
Labels: enhancement

#45 Feat(timeline): added aos
  .prettierrc
  package.json
  pnpm-lock.yaml
  src/app.jsx
  src/components/common/blocks/insight.jsx
  src/components/common/typography/body.jsx
  src/components/common/typography/heading.jsx
  src/components/common/typography/sub-heading.jsx
  src/components/landing/vision/index.jsx
  src/components/landing/vision/timeline.jsx
Labels: enhancement

#51 Highlight header github icon and footer socials on hover
  src/components/common/layout/footer.jsx
  src/components/common/layout/header.jsx
  src/styles/index.css
  tailwind.config.js
Labels: changed requested :eyes:

#48 Draft: documentation pages
  .eslintrc
  .prettierrc
  index.html
  package.json
  pnpm-lock.yaml
  src/app.jsx
  src/components/common/accordion/index.jsx
  src/components/common/blocks/insight.jsx
  src/components/common/buttons/primary.jsx
  src/components/common/index.jsx
  src/components/common/layout/footer.jsx
  src/components/common/layout/header.jsx
  src/components/common/layout/index.jsx
  src/components/common/scroll-to-top.jsx
  src/components/common/tabs/index.jsx
  src/components/common/terminal/terminal-group.jsx
  src/components/docs/breadcrumbs.jsx
  src/components/docs/cards/index.jsx
  src/components/docs/cards/status-card.jsx
  src/components/docs/explorer.jsx
  src/components/docs/index.jsx
  src/components/docs/navigation/core.jsx
  src/components/docs/navigation/index.jsx
  src/components/docs/navigation/mobile.jsx
  src/components/docs/shell/index.jsx
  src/components/docs/shell/installer.jsx
  src/components/docs/shell/shell.jsx
  src/components/docs/shell/tabs.jsx
  src/components/landing/console/index.jsx
  src/components/landing/hero.jsx
  src/components/landing/vision/index.jsx
  src/constants/hyperlinks.js
  src/hooks/index.js
  src/hooks/title.js
  src/hooks/window-dimension.js
  src/icons/babel.jsx
  src/icons/index.jsx
  src/icons/vscode.jsx
  src/pages/docs/configuration.mdx
  src/pages/docs/getting-started.mdx
  src/pages/docs/index.jsx
  src/pages/docs/installation.mdx
  src/pages/docs/meta.json
  src/pages/docs/underlying-dependencies/functions/clean-tracing.mdx
  src/pages/docs/underlying-dependencies/functions/disable-tracing.mdx
  src/pages/docs/underlying-dependencies/functions/express-middleware.mdx
  src/pages/docs/underlying-dependencies/functions/installation.mdx
  src/pages/docs/underlying-dependencies/functions/simple-usage.mdx
  src/pages/docs/underlying-dependencies/module-logger/installation.mdx
  src/pages/docs/underlying-dependencies/module-logger/options.mdx
  src/pages/docs/underlying-dependencies/module-logger/simple-usage.mdx
  src/pages/index.jsx
  src/styles/animations/index.css
  src/styles/animations/keyframes.css
  src/styles/colors.css
  src/styles/index.css
  src/utils/index.js
  tailwind.config.js
  vite.config.js
Labels: documentation, enhancement

#65 Dhruv branch
  package-lock.json
  src/components/common/layout/footer.jsx
  src/components/common/layout/header.jsx
  src/icons/timekeeper.jsx
  tailwind.config.js
Labels: changed requested :eyes:, enhancement

#69 Fix: footer timekeeper logo blackening on doc routes
  pnpm-lock.yaml
  src/icons/timekeeper.jsx
Labels: bug

#70 Fix: remove logo outline
  src/styles/index.css
Labels: changed requested :eyes:

#41 fix: link footer socials with actual pages
  src/components/common/layout/footer.jsx
  src/constants/index.js
  src/constants/socials.js
Labels: review needed :guard:

#89 Fix(console): mobile responsiveness
  src/components/common/terminal/terminal-group.jsx
  src/components/common/terminal/terminal.jsx
  src/components/landing/console/index.jsx
  src/styles/index.css
Labels: changed requested :eyes:
